version: '3'
services:
  main:
    build: docker
    volumes:
      - .:/root/GNN
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]