version: '3'
services:
  app:
    build: .
    volumes:
      - .:/root/MD-GNN
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
